### ISSUE TITLE
confirm edit to SPECS.md introduction

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/fn-adaptive-sampling#2]
@HughSt Are you happy with this as an updated intro to _fn-adaptive-sampling_ `SPECS.md`:

> Take a GeoJSON FeatureCollection of points with observations and prediction points, with uncertainty values, and we'll recommend the next _n_ sites to survey in order to minimize uncertainty.

**Comment by HughSt** [comment]
You OK with these minor additions?

Take a GeoJSON FeatureCollection of points with observations and prediction points, with uncertainty values from model predictions, and we'll recommend the next n sites to survey in order to minimize uncertainty when updating the same model.

**Comment by onlyjsmith** [comment]
Yup

**Comment by onlyjsmith** [comment]
I've edited SPECS.md to include your text. Closing.
