### ISSUE TITLE
return all the points, with extra column to indicate 'selected for survey'

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/fn-adaptive-sampling#3]
At the moment we're outputting _only_ the recommended sites to survey. 

Wondering if we can output instead the whole of the input (i.e. all the points), and make clear with some field, which are the ones to be surveyed.

We're getting close to being able to use the same input and output formats for both this and `fn-prev-pred`. This might make handling data coming in and out of these functions much simpler.

What do you think? Is there already a column that's output that we can use to infer or mark that it is recommended for the next survey?

**Comment by HughSt** [comment]
No problem - I can edit to provide this output. Will confirm here when complete.

**Comment by HughSt** [comment]
OK now returns all points with `adaptively_selected` field (0/1)

**Comment by onlyjsmith** [comment]
Awesome!
